import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    button: "src/button.tsx",
    badge: "src/badge.tsx",
    alert: "src/alert.tsx",
    card: "src/card.tsx",
    divider: "src/divider.tsx",
    avatar: "src/avatar.tsx",
    spinner: "src/spinner.tsx",
    progress: "src/progress.tsx",
    skeleton: "src/skeleton.tsx",
    chip: "src/chip.tsx",
    "icon-button": "src/icon-button.tsx",
    "text-field": "src/text-field.tsx",
    textarea: "src/textarea.tsx",
    select: "src/select.tsx",
    checkbox: "src/checkbox.tsx",
    radio: "src/radio.tsx",
    switch: "src/switch.tsx",
    tabs: "src/tabs.tsx",
    breadcrumbs: "src/breadcrumbs.tsx",
    pagination: "src/pagination.tsx",
    tooltip: "src/tooltip.tsx",
    popover: "src/popover.tsx",
    dialog: "src/dialog.tsx",
    portal: "src/portal.tsx",
    "dropdown-menu": "src/dropdown-menu.tsx",
    appbar: "src/appbar.tsx",
    toast: "src/toast.tsx",
    accordion: "src/accordion.tsx",
    table: "src/table.tsx",
    drawer: "src/drawer.tsx",
    navbar: "src/navbar.tsx",
    "segmented-control": "src/segmented-control.tsx",
    "input-group": "src/input-group.tsx",
    box: "src/box.tsx",
    stack: "src/stack.tsx",
    grid: "src/grid.tsx",
    "theme/ThemeProvider": "src/theme/ThemeProvider.tsx",
  },
  format: ["esm", "cjs"],
  dts: true,
  outExtension: ({ format }) => (format === "esm" ? ".mjs" : ".cjs"),
  external: ["react", "react-dom", "tailwindcss"],
  clean: true,
});
